name: booking_room
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  firebase_auth: ^5.3.1
  flutter_spinkit: ^5.2.1
  firebase_core: any
  cloud_firestore: ^5.4.4
  image_picker: ^1.1.1
  carousel_slider: ^5.0.0
  firebase_storage: ^12.3.3
  google_ml_vision: ^0.0.8
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  table_calendar: ^3.1.2
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  http: ^1.2.2
  animations: ^2.0.11



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

